# Generated by Django 4.2.16 on 2024-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Meat', 'Meat'), ('Vegetable', 'Vegetable'), ('Dairy', 'Dairy'), ('Fruit', 'Fruit')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredient/')),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
