# Generated by Django 4.2.16 on 2024-11-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_alter_ingredient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apps/ingredient/media/'),
        ),
    ]
