# Generated by Django 5.1.2 on 2024-11-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='ingredienttobuy',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='IngredientInCart',
        ),
    ]
