# Generated by Django 5.1.1 on 2024-11-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Vegetable', 'Vegetable'), ('Dairy', 'Dairy'), ('Fruit', 'Fruit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient/'),
        ),
    ]
