# Generated by Django 5.1.1 on 2024-11-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_alter_ingredient_category_alter_ingredient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Vegetable', 'Vegetable'), ('Dairy', 'Dairy'), ('Fruit', 'Fruit')], max_length=100),
        ),
    ]
